version: 2.1

setup: true

orbs:
  config-splitting: circle-makotom-orbs/config-splitting@0.0.1

jobs:
  shared-job:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo "A job from the main config!"

workflows:
  setup-config-files:
    jobs:
      # Specify the file listing configs to be combined in `config-list-file`
      # This job combines those listed configs, then execute the resulting config.
      - shared-job
      - config-splitting/run-all-modular-configs:
          filters:
            branches:
              only:
                - main
          config-list-file: .circleci/modular-config-list-main.txt
          requires:
            - shared-job
      - config-splitting/run-all-modular-configs:
          filters:
            branches:
              ignore:
                - main
          config-list-file: .circleci/modular-config-list-feature.txt
          requires:
            - shared-job

# VS Code Extension Version: 1.1.1